trigger:
- main

pr:
  branches:
    include:
    - main
  drafts: false

jobs:
- job: IntegrationTest
  displayName: Integration test
  strategy:
    matrix:
      cuda12:
        containerImage: ghcr.io/microsoft/mscclpp/mscclpp:base-dev-cuda12.4

  pool:
    name: mscclpp
  container:
    image: $[ variables['containerImage'] ]
    options: --privileged --ipc=host --gpus=all --ulimit memlock=-1:-1

  steps:
  - task: Bash@3
    name: Build
    displayName: Build
    inputs:
      targetType: 'inline'
      script: |
        make -j src.build CUDA_HOME=/usr/local/cuda-12 NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80"
        export MSCCL_EXECUTOR_BUILD_PATH=$(pwd)/build
        git clone https://github.com/Azure/msccl-scheduler.git
        git clone https://github.com/Azure/msccl-tests-nccl.git
        cd msccl-tests-nccl
        export PATH=/usr/local/mpi/bin:$PATH
        make MPI=1 MPI_HOME=/usr/local/mpi CUDA_HOME=/usr/local/cuda-12 NCCL_HOME=$MSCCL_EXECUTOR_BUILD_PATH -j
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: LockGPUClock
    displayName: Lock GPU clock frequency
    inputs:
      targetType: 'inline'
      script: |
        sudo nvidia-smi -pm 1
        for i in $(seq 0 $(( $(nvidia-smi -L | wc -l) - 1 ))); do
          sudo nvidia-smi -ac $(nvidia-smi --query-gpu=clocks.max.memory,clocks.max.sm --format=csv,noheader,nounits -i $i | sed 's/\ //') -i $i
        done
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: AllGatherTest
    displayName: Run msccl AllGather test
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/all_gather_perf -b 1K -e 1G -f 2 -o output.jsonl
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: SendRecvTest
    displayName: Run msccl SendRecv test
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/sendrecv_perf -b 1K -e 1G -f 2 -o output.jsonl
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: AllReduceTest
    displayName: Run msccl AllReduce test
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/all_reduce_perf -b 1K -e 1G -f 2 -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/all_reduce_perf -b 1K -e 1G -f 2 -d half -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/all_reduce_perf -b 1K -e 1G -f 2 -d fp8_e4m3 -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/all_reduce_perf -b 1K -e 1G -f 2 -d fp8_e5m2 -o output.jsonl
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: AllToAllTest
    displayName: Run msccl AllToAll test
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/alltoall_perf -b 1K -e 1G -f 2 -o output.jsonl
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: ReduceScatterTest
    displayName: Run msccl ReduceScatter test
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/reduce_scatter_perf -b 1K -e 1G -f 2 -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/reduce_scatter_perf -b 1K -e 1G -f 2 -d half -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/reduce_scatter_perf -b 1K -e 1G -f 2 -d fp8_e4m3 -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/reduce_scatter_perf -b 1K -e 1G -f 2 -d fp8_e5m2 -o output.jsonl
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: AllGatherTestWithAlgorithm
    displayName: Run msccl AllGather test with MSCCL algorithm XML
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        export MSCCL_ALGO_DIR=$(pwd)/msccl-scheduler/tools/msccl-algorithms/ndv4
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/all_gather_perf -b 1K -e 1G -f 2 -o output.jsonl
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: SendRecvTestWithAlgorithm
    displayName: Run msccl SendRecv test with MSCCL algorithm XML
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        export MSCCL_ALGO_DIR=$(pwd)/msccl-scheduler/tools/msccl-algorithms/ndv4
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/sendrecv_perf -b 1K -e 1G -f 2 -o output.jsonl
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: AllReduceTestWithAlgorithm
    displayName: Run msccl AllReduce test with MSCCL algorithm XML
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        export MSCCL_ALGO_DIR=$(pwd)/msccl-scheduler/tools/msccl-algorithms/ndv4
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/all_reduce_perf -b 1K -e 1G -f 2 -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/all_reduce_perf -b 1K -e 1G -f 2 -d half -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/all_reduce_perf -b 1K -e 1G -f 2 -d fp8_e4m3 -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/all_reduce_perf -b 1K -e 1G -f 2 -d fp8_e5m2 -o output.jsonl
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: AllToAllTestWithAlgorithm
    displayName: Run msccl AllToAll test with MSCCL algorithm XML
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        export MSCCL_ALGO_DIR=$(pwd)/msccl-scheduler/tools/msccl-algorithms/ndv4
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/alltoall_perf -b 1K -e 1G -f 2 -o output.jsonl
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: ReduceScatterTestWithAlgorithm
    displayName: Run msccl ReduceScatter test with MSCCL algorithm XML
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        export MSCCL_ALGO_DIR=$(pwd)/msccl-scheduler/tools/msccl-algorithms/ndv4
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/reduce_scatter_perf -b 1K -e 1G -f 2 -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/reduce_scatter_perf -b 1K -e 1G -f 2 -d half -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/reduce_scatter_perf -b 1K -e 1G -f 2 -d fp8_e4m3 -o output.jsonl
        mpirun --allow-run-as-root -np 8 -x LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_MSCCL_ENABLE=1 ./msccl-tests-nccl/build/reduce_scatter_perf -b 1K -e 1G -f 2 -d fp8_e5m2 -o output.jsonl
      workingDirectory: '$(System.DefaultWorkingDirectory)'
